### PR TITLE
commiting paper rmd and md and cleanup and download source files

### PR DESCRIPTION
**Pull request by NSHAVER1**
creating a pull request for Q3ii-rmd, md, cleanup and download code

### CODE REVIEW

**Review by JackNelson — COMMENTED** [review]
Nicole,
All of this looks great!  I only have one initial comment.  I was afraid this would happen but it appears we dual pathed cleaning up the temp.csv dataset.  I was going to suggest that I approve the merge and then update the cleanup_2 document with some additional cleanup.  In my file it splits the temp set into two subsets, I convert the "yyyy-mm-dd" and "mm/dd/yyyy" date formats separately, union the two sets back together, and remove na values in $Monthly.AverageTemp.  This way we have a cleaned data set of all the original data and we can subset in beginning of our .Rmd for only observations beyond 1/1/1900.  Please let me know what you think.  Then I can approve carry out whatever direction we decide.  Thanks again!

**Comment by NSHAVER1** [comment]
Your method is great! Use that for the cleanup and import parts and just get rid of what I did. I will adjust my code for Q3ii to subset the 1900 and later data. 

Please just keep my Q3ii section, and make sure you get all of the packages that I added to the top section.

**Comment by JackNelson** [comment]
Sounds like a plan!  Will do.

**Review by JackNelson — APPROVED** [review]
Approving pull request.

**Pull request merged**
